<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <UseWindowsForms>true</UseWindowsForms>
    <ImplicitUsings>enable</ImplicitUsings>
    <EPPlusLicenseContext>NonCommercial</EPPlusLicenseContext>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="EPPlus" Version="8.2.1" />
    <PackageReference Include="Microsoft.Web.WebView2" Version="1.0.3595.46" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\HomeTaxEditor.Core\HomeTaxEditor.Core.csproj" />
  </ItemGroup>

</Project>